/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdbool.h>
#include <math.h>

#include "bakery.h"

#define MAX_CLNT_CNT 128

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3

static bool choosing[MAX_CLNT_CNT] = {false};
static int numbers[MAX_CLNT_CNT] = {0};
static int pids[MAX_CLNT_CNT] = {0};

int max_number() {
	int res = numbers[0];
	for (int i = 1; i < MAX_CLNT_CNT; ++i)
		if (numbers[i] > res)
			res = numbers[i];
	return res;
}

int *
get_number_1_svc(struct REQUEST *argp, struct svc_req *rqstp) {
	static int  result;
	printf("Client (pid = %d) logged to server.\n", argp->pid);
	pids[argp->idx] = argp->pid;
	choosing[argp->idx] = true;
	result = numbers[argp->idx] = max_number() + 1;
	choosing[argp->idx] = false;

	return &result;
}

float *
bakery_service_1_svc(struct REQUEST *argp, struct svc_req *rqstp) {
	static float result = 0.0;
	for (int i = 0; i < MAX_CLNT_CNT; i++) {
		if (choosing[i]) {
			printf("Client (pid = %d, no = %d): client %d is still choosing a number.\n", argp->pid, argp->num, i);
			result = INFINITY;
			return &result;
		}
		if (numbers[i] != 0 && (numbers[i] < numbers[argp->idx] || 
                                (numbers[i] == numbers[argp->idx] && pids[i] < pids[argp->idx]))) {
			printf("Client (pid = %d, no = %d): client %d's number has higher priority (no = %d).\n", argp->pid, argp->num, i, numbers[i]);
			result = INFINITY;
            return &result;
        }
	}
	switch(argp->op) {
		case(ADD): {
			result = argp->arg1 + argp->arg2;
			break;
		}
		case(SUB): {
			result = argp->arg1 - argp->arg2;
			break;
		}
		case(MUL): {
			result = argp->arg1 * argp->arg2;
			break;
		}
		case(DIV): {
			if (argp->arg2 == 0.0)
				printf("Client (pid = %d) div by zero, default result = 0.0\n", argp->pid);
			else
				result = argp->arg1 / argp->arg2;
			break;
		}
		default: {
			printf("Client (pid = %d) operation not found, default result = 0.0\n", argp->pid);
			break;
		}
	}
	printf("Client (pid = %d, no = %d) got result: %lf\n", argp->pid, argp->num, result);
	numbers[argp->idx] = 0;
	choosing[argp->idx] = false;

	return &result;
}