/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/wait.h>
#include <rpc/rpc.h>

#include "prodcons.h"

#define CLNT_CNT 20
#define OP_CNT 2
#define ATTEMPTS 30

#define CNAME "CONSUMER"
#define PNAME "PRODUCER"

void
prodcons_prog_1(char *host, int idx)
{	
	CLIENT *clnt;
	REQUEST req; 
	int  *res;
	req.pid = getpid();
	srand((unsigned int)(time(NULL) ^ req.pid));
	sleep(rand() % 3 + 1);
	req.op = ((idx == 0) || (rand() % 2 == 0)) ? PRODUCER : CONSUMER;
	req.idx = idx;
	req.res = 0;

#ifndef	DEBUG
	clnt = clnt_create (host, PRODCONS_PROG, PRODCONS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	struct timeval timeout;
    timeout.tv_sec = 60;
    timeout.tv_usec = 0;
    if (clnt_control(clnt, CLSET_TIMEOUT, (char *)&timeout) == FALSE) {
        fprintf(stderr, "Failed to set timeout\n");
        clnt_destroy(clnt);
        exit(1);
    }
#endif	/* DEBUG */
	switch(req.op) {
		case(CONSUMER): {
			int i = 0;
			for (; i < ATTEMPTS; ++i) {
				res = consumer_1(&req, clnt);
				req.res = (*res);
				if (res != NULL && (req.res >= 'a' && req.res <= 'z'))
					break;
				else if (res == (int *) NULL) {
					req.res = -1;
					clnt_perror (clnt, "call failed");
					break;
				}
				else
					sleep(1);
			}
			printf("i: %d\n", i);
			break;
		}
		case(PRODUCER): {
			int i = 0;
			for (; i < ATTEMPTS; ++i) {
				res = producer_1(&req, clnt);
				req.res = (*res);
				if (res != NULL && (req.res >= 'a' && req.res <= 'z')) {
					break;
				} else if (res == (int *) NULL) {
					req.res = -1;
					clnt_perror (clnt, "call failed");
					break;
				}
				else {
					sleep(1);
				}
			}
			break;
		}
		default: {
			printf("client (pid = %d): undefined operation %d.\n", req.pid, req.op);
			exit(1);
		}
	}
	char *name = (req.op == 2) ? CNAME : PNAME;
	if (req.res == -1) 
		printf("client (pid = %d, id = %d) - %s: invalid result\n", req.pid, req.idx, name);
	else
		printf("client (pid = %d, id = %d) - %s: %c\n", req.pid, req.idx, name, req.res);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	char *host = argv[1];
	pid_t clnt_pid[CLNT_CNT];
	for (size_t i = 0; i < CLNT_CNT; ++i) {
		if ((clnt_pid[i] = fork()) == -1) {
			perror("can't fork\n");
			exit(1);
		} else if (clnt_pid[i] == 0) {
			prodcons_prog_1(host, i);
			exit(0);
		}
		srand((unsigned int)time(NULL) ^ clnt_pid[i]);
		sleep(rand() % 3);
	}
	for (size_t i = 0; i < CLNT_CNT; i++) {
		int status;
		waitpid(clnt_pid[i], &status, 0);
	}
	printf("PARENT CLIENT EXITED.\n");
exit (0);
}
